### ISSUE TITLE
你好 在使用的过程中出现一个问题

### ISSUE THREAD

**Issue by CatyVon** [arvinljw/PictureSelector#4]
java.lang.RuntimeException: 
Unable to start activity ComponentInfo{com.harmight.dubbing/net.arvin.selector.uis.SelectorActivity}: java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation

Caused by: java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation

报错日志如上  请问你那边有解决方案么  测试机为小米mix2

**Comment by arvinljw** [comment]
在配置文件中SelectorActivity的申明时加入这一句了么

android:screenOrientation="portrait"

**Comment by CatyVon** [comment]
已经添加了  没有变化  并且根据网上的资料 修改style中的android:windowIsTranslucent  依旧没有变化  

发送自 Windows 10 版邮件应用

发件人: arvinljw
发送时间: 2018年4月17日 13:31
收件人: arvinljw/PictureSelector
抄送: Monce; Author
主题: Re: [arvinljw/PictureSelector] 你好 在使用的过程中出现一个问题 (#4)

在配置文件中SelectorActivity的申明时加入这一句了么
android:screenOrientation="portrait"

**Comment by arvinljw** [comment]
试试demo运行有没有问题呢，我的小米8.1的系统运行demo没有出错。

**Comment by tao756772787** [comment]
05-08 01:17:06.841 10542-10552/? E/zygote64: Failed sending reply to debugger: Broken pipe
05-08 01:17:55.504 10542-10791/net.arvin.selectordemo E/AndroidRuntime: FATAL EXCEPTION: Thread-6
    Process: net.arvin.selectordemo, PID: 10542
    android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
        at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:7307)
        at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1159)
        at android.view.View.requestLayout(View.java:21926)
        at android.view.View.requestLayout(View.java:21926)
        at android.view.View.requestLayout(View.java:21926)
        at android.view.View.requestLayout(View.java:21926)
        at android.view.View.requestLayout(View.java:21926)
        at android.view.View.requestLayout(View.java:21926)
        at android.view.View.requestLayout(View.java:21926)
        at android.view.View.requestLayout(View.java:21926)
        at android.support.v7.widget.RecyclerView.requestLayout(RecyclerView.java:3970)
        at android.support.v7.widget.RecyclerView$RecyclerViewDataObserver.onChanged(RecyclerView.java:5060)
        at android.support.v7.widget.RecyclerView$AdapterDataObservable.notifyChanged(RecyclerView.java:11540)
        at android.support.v7.widget.RecyclerView$Adapter.notifyDataSetChanged(RecyclerView.java:6762)
        at net.arvin.selector.uis.fragments.SelectorFragment$1.dataCallback(SelectorFragment.java:81)
        at net.arvin.selector.data.FileData$1.run(FileData.java:69)
        at java.lang.Thread.run(Thread.java:764)

**Comment by CatyVon** [comment]
android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.

这句提示线程调用错误  只有主线程才能修改UI

发送自 Windows 10 版邮件应用

发件人: tao756772787
发送时间: 2018年5月8日 1:18
收件人: arvinljw/PictureSelector
抄送: Monce; Author
主题: Re: [arvinljw/PictureSelector] 你好 在使用的过程中出现一个问题 (#4)

05-08 01:17:06.841 10542-10552/? E/zygote64: Failed sending reply to debugger: Broken pipe
05-08 01:17:55.504 10542-10791/net.arvin.selectordemo E/AndroidRuntime: FATAL EXCEPTION: Thread-6
Process: net.arvin.selectordemo, PID: 10542
android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:7307)
at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1159)
at android.view.View.requestLayout(View.java:21926)
at android.view.View.requestLayout(View.java:21926)
at android.view.View.requestLayout(View.java:21926)
at android.view.View.requestLayout(View.java:21926)
at android.view.View.requestLayout(View.java:21926)
at android.view.View.requestLayout(View.java:21926)
at android.view.View.requestLayout(View.java:21926)
at android.view.View.requestLayout(View.java:21926)
at android.support.v7.widget.RecyclerView.requestLayout(RecyclerView.java:3970)
at android.support.v7.widget.RecyclerView$RecyclerViewDataObserver.onChanged(RecyclerView.java:5060)
at android.support.v7.widget.RecyclerView$AdapterDataObservable.notifyChanged(RecyclerView.java:11540)
at android.support.v7.widget.RecyclerView$Adapter.notifyDataSetChanged(RecyclerView.java:6762)
at net.arvin.selector.uis.fragments.SelectorFragment$1.dataCallback(SelectorFragment.java:81)
at net.arvin.selector.data.FileData$1.run(FileData.java:69)
at java.lang.Thread.run(Thread.java:764)

**Comment by arvinljw** [comment]
嗯，发现了，我的手机居然没有报这个错，但是确实要在主线程去修改才对，下个版本修改了

**Comment by CatyVon** [comment]
只要牵扯到UI刷新修改的  都必须回到主线程  不然就会出现 CalledFromWrongThreadException 这个异常的 所以修改刷新的时候一定记得回到主线程修改
发送自 Windows 10 版邮件应用

发件人: arvinljw
发送时间: 2018年5月8日 9:49
收件人: arvinljw/PictureSelector
抄送: Monce; Author
主题: Re: [arvinljw/PictureSelector] 你好 在使用的过程中出现一个问题 (#4)

嗯，发现了，我的手机居然没有报这个错，但是确实要在主线程去修改才对，v2.0.4修改了

**Comment by arvinljw** [comment]
好的，感谢～
