### ISSUE TITLE
调用选择图片会奔溃

### ISSUE THREAD

**Issue by Haowensheng** [arvinljw/PictureSelector#8]
2019-04-21 11:56:25.173 15544-15544/com.d2p9.inteligentsite.photoselector E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.d2p9.inteligentsite.photoselector, PID: 15544
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.d2p9.inteligentsite.photoselector/net.arvin.selector.uis.SelectorActivity}: android.view.InflateException: Binary XML file line #10: Binary XML file line #10: Error inflating class android.support.v7.widget.RecyclerView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2854)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2929)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1618)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6696)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
     Caused by: android.view.InflateException: Binary XML file line #10: Binary XML file line #10: Error inflating class android.support.v7.widget.RecyclerView
     Caused by: android.view.InflateException: Binary XML file line #10: Error inflating class android.support.v7.widget.RecyclerView
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v7.widget.RecyclerView" on path: DexPathList[[zip file "/data/app/com.d2p9.inteligentsite.photoselector-oV15sTvMlw2Zc3i27MM_2A==/base.apk", zip file "/data/app/com.d2p9.inteligentsite.photoselector-oV15sTvMlw2Zc3i27MM_2A==/split_lib_dependencies_apk.apk", zip file "/data/app/com.d2p9.inteligentsite.photoselector-oV15sTvMlw2Zc3i27MM_2A==/split_lib_resources_apk.apk", zip file "/data/app/com.d2p9.inteligentsite.photoselector-oV15sTvMlw2Zc3i27MM_2A==/split_lib_slice_0_apk.apk", zip file "/data/app/com.d2p9.inteligentsite.photoselector-oV15sTvMlw2Zc3i27MM_2A==/split_lib_slice_1_apk.apk", zip file "/data/app/com.d2p9.inteligentsite.photoselector-oV15sTvMlw2Zc3i27MM_2A==/split_lib_slice_2_apk.apk", zip file "/data/app/com.d2p9.inteligentsite.photoselector-oV15sTvMlw2Zc3i27MM_2A==/split_lib_slice_3_apk.apk", zip file "/data/app/com.d2p9.inteligentsite.photoselector-oV15sTvMlw2Zc3i27MM_2A==/split_lib_slice_4_apk.apk", zip file "/data/app/com.d2p9.inteligentsite.photoselector-oV15sTvMlw2Zc3i27MM_2A==/split_lib_slice_5_apk.apk", zip file "/data/app/com.d2p9.inteligentsite.photoselector-oV15sTvMlw2Zc3i27MM_2A==/split_lib_slice_6_apk.apk", zip file "/data/app/com.d2p9.inteligentsite.photoselector-oV15sTvMlw2Zc3i27MM_2A==/split_lib_slice_7_apk.apk", zip file "/data/app/com.d2p9.inteligentsite.photoselector-oV15sTvMlw2Zc3i27MM_2A==/split_lib_slice_8_apk.apk", zip file "/data/app/com.d2p9.inteligentsite.photoselector-oV15sTvMlw2Zc3i27MM_2A==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.d2p9.inteligentsite.photoselector-oV15sTvMlw2Zc3i27MM_2A==/lib/arm64, /system/lib64, /system/vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.view.LayoutInflater.createView(LayoutInflater.java:610)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:794)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:867)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:519)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at net.arvin.selector.uis.fragments.BaseFragment.onCreateView(BaseFragment.java:62)
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2346)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1428)
2019-04-21 11:56:25.180 15544-15544/com.d2p9.inteligentsite.photoselector E/AndroidRuntime:     at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3248)
        at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3200)
        at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:195)
        at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:597)
        at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1334)
        at android.app.Activity.performStart(Activity.java:7057)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2929)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1618)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6696)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
    	Suppressed: java.io.IOException: No original dex files found for dex location /data/app/com.d2p9.inteligentsite.photoselector-oV15sTvMlw2Zc3i27MM_2A==/split_lib_resources_apk.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:353)
        at dalvik.system.DexFile.<init>(DexFile.java:100)
        at dalvik.system.DexFile.<init>(DexFile.java:74)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:374)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
        at dalvik.system.DexPathList.<init>(DexPathList.java:157)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.PathClassLoaderFactory.createClassLoader(PathClassLoaderFactory.java:43)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:69)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:36)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:681)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:714)
        at android.app.LoadedApk.getResources(LoadedApk.java:941)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2254)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5753)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688)
        		... 6 more
    	Suppressed: java.io.IOException: No original dex files found for dex location /data/app/com.d2p9.inteligentsite.photoselector-oV15sTvMlw2Zc3i27MM_2A==/split_lib_slice_3_apk.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:353)
        at dalvik.system.DexFile.<init>(DexFile.java:100)
        at dalvik.system.DexFile.<init>(DexFile.java:74)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:374)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
        at dalvik.system.DexPathList.<init>(DexPathList.java:157)
2019-04-21 11:56:25.182 15544-15544/com.d2p9.inteligentsite.photoselector E/AndroidRuntime:     at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.PathClassLoaderFactory.createClassLoader(PathClassLoaderFactory.java:43)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:69)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:36)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:681)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:714)
        at android.app.LoadedApk.getResources(LoadedApk.java:941)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2254)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5753)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688)
        		... 6 more
    	Suppressed: java.io.IOException: No original dex files found for dex location /data/app/com.d2p9.inteligentsite.photoselector-oV15sTvMlw2Zc3i27MM_2A==/split_lib_slice_6_apk.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:353)
        at dalvik.system.DexFile.<init>(DexFile.java:100)
        at dalvik.system.DexFile.<init>(DexFile.java:74)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:374)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
        at dalvik.system.DexPathList.<init>(DexPathList.java:157)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.PathClassLoaderFactory.createClassLoader(PathClassLoaderFactory.java:43)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:69)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:36)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:681)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:714)
        at android.app.LoadedApk.getResources(LoadedApk.java:941)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2254)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5753)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688)
        		... 6 more

**Comment by arvinljw** [comment]
RecyclerView没有找到，是不是被移除了？

**Comment by Haowensheng** [comment]
不怎么清楚但是我感觉是路径的问题 ,他找不到那个Activity 但是我已经在Mainifest中配置了 有点懵
